### ISSUE TITLE
user can choose wildflower

### ISSUE THREAD

**Issue by deliotclarke** [snuggle-destruction/Trestlebridge-Farms#27]
Given a user has launched the program
When the user selects the option to purchase seed
Then the user should be presented with a list of seeds to purchase

Given user is viewing a list of seeds
When the user selects a seed
Then the user should be presented with a list of potential seed fields

Given user is viewing the list of potential seed fields
When the user selects a field
And the field is capable of growing the plant
Then the user should be taken back to the main menu

Given user is viewing the list of potential seed fields
When the user selects a field
And the field is incapable of growing the plant
Then the user should be presented with a message to select another field
And the list of fields should be shown again

**Comment by Jdriscoll1993** [comment]
"Given user is viewing the list of potential seed fields
When the user selects a field
And the field is incapable of growing the plant
Then the user should be presented with a message to select another field
And the list of fields should be shown again" 
^^^
right now the program is set up so you'll only be given the option to plant seeds at capable farms. We should look at this as a group and discuss how to implement displaying all the fields for every seed and giving the user an error message when they try to plant a seed at an incapable field.
